# These are supported funding model platforms

# github: daimor
custom: ['https://www.paypal.me/daimor', 'https://money.yandex.ru/to/410018360447959']
patreon: daimor
ko_fi: daimor
liberapay: daimor
# open_collective: daimor

